#!/usr/bin/env node
var next = require("next");
var dev = process.env.NODE_ENV !== "production";
var app = next({ dev });
var handle = app.getRequestHandler();
var port = normalizePort(process.env.PORT || '3000');

app.prepare().then(() => {
  var server = require('./app');

  server.all("*", (req, res) => {
    return handle(req, res);
  });

  server.listen(port, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});

function normalizePort(val) {
  var port = parseInt(val, 10);

  if (isNaN(port)) {
    return val;
  }

  if (port >= 0) {
    return port;
  }

  return false;
}